version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.7
  install:
    - requirements: pip-requirements-docs.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
